# container base https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system
sudo: false
dist: trusty

branches:
  only:
    - master
    - fix-travis

language: go

go:
  - "1.11"

env:
  global:
    - GOOS=linux
    - GOARCH=amd64

cache:
  directories:
  - vendor
  - $GOPATH/bin

before_install:
  - export PATH=$PATH:$GOPATH/bin

install:
  - make install

script:
  - make test
  - make build

after_success:
  - make artifacts.tgz

addons:
  artifacts:
    paths:
      - artifacts.tgz
    bucket: sunrise2018-hakaru-artifacts
    target_paths: latest:$TRAVIS_COMMIT
    s3_region: ap-northeast-1
